### ISSUE TITLE
获取了解压密码 但是解压失败了

### ISSUE THREAD

**Issue by 1226676454** [lenve/javadoc#2]
获取了解压密码 但是解压失败了

**Comment by lenve** [comment]
Mac 下请用 The Unarchiver 解压

**Comment by 1226676454** [comment]
好的，谢谢指导



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月15日(星期四) 下午5:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lenve/javadoc] 获取了解压密码 但是解压失败了 (#2)





 
Mac 下请用 The Unarchiver 解压
